### ISSUE TITLE
压缩后模型并未减小

### ISSUE THREAD

**Issue by subshall** [HolmesShuan/Label-free-Network-Compression#1]
压缩后模型并未减小,使用caffe推理的时候速度反而变慢了，请问是因为什么

**Comment by HolmesShuan** [comment]
1. About the model size

We still use float32 to store the 4-bit  weights, so that Caffe can read the generated `.caffemodel`. If you wonder whether weights are indeed 4-bit, you may use **zip** or **7z** compression technique to check the compressed model size. 

2. About the inference speed

4-bit weights & 8-bit activations have **not** been supported by the modern CPU or GPU, which means no speedup. We add a scale layer after each convolution layer to hold weights scale terms, which takes extra computing cost. This algorithm aims at custom hardware such as FPGA. [Here](https://github.com/HolmesShuan/CNN-Inference-Engine-Quick-View) are some useful inference libs you may have an interest, especially [NCNN](https://github.com/Tencent/ncnn/wiki/quantized-int8-inference).
